= Active Matter Update
// Wendell Smith
:source-highlighter: pygments
:pygments-style: autumn
:revealjs_theme: simple
:revealjs_transition: none
:revealjs_width: 1280
:revealjs_height: 960
:revealjs_margin: 0.04
:revealjs_history: false
// :revealjsdir: https://wackywendell.github.io/reveal.js/
:revealjsdir: ..
// :revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.0.0/
:stem: latexmath
:imagesdir: imgs
// :toc:

== Review: Temperature and Activity

[cols="^a,^a",grid="none",frame="none"]
|==================================
| Temperature | Activity

| Brownian thermostat set to some \(T\)
| Brownian thermostat set to \(T=1\)

| Thermostat keeps \(T\) fixed
| Activity raises temperature due to energy input

|==================================

=== Review: Temperature and Activity

image::randkick4-MSD-f0.62-R20-N100.svg["", 100%, title="", caption="", align=center]

=== Plan: Use a Harmonic Potential

 * The current repulsive Lennard-Jones may be too similar to hard-spheres, and may be unaffected by \(20 k_B T\) "jolts"
 * A softer potential may provide lower "barriers" that can be jumped with a \(20 k_B T\) "jolt"

=== Results: Harmonic Potential

image::randkick4H-MSD-f0.72-R20-N40-e72.svg["", 100%, title="", caption="", align=center]

=== Results: Harmonic Potential

image::randkick4H-MSD-f0.68-R20-N40-e1000.svg["", 100%, title="", caption="", align=center]

Thought: Perhaps its that the longer the plateau, the greater the effect of random activity.

== Review: Maximal \(\alpha_2\)

image::rsqsbis5-MSD-t2000.svg["", 100%, title="", caption="", align=center]

=== Review: Maximal \(\alpha_2\)

From the MSDs, we get \(\alpha_2\):

image::rsqsbis5-a2-t2000.svg["", 100%, title="", caption="", align=center]

=== Review: Maximal \(\alpha_2\)

Some simulations, however, have not relaxed in the time I left them running.

image::rsqsbis5-relaxtimes.svg["", 60%, title="", caption="", align=center]

=== Review: Maximal \(\alpha_2\)

Simulations that have not relaxed do not have fixed results. If we remove those simulations, this is the plot of \(\alpha_2\) we are left with.

image::rsqsbis5-a2-relaxed-t2000.svg["", 100%, title="", caption="", align=center]
