= α₂ Close to Jamming
// Wendell Smith
:source-highlighter: pygments
:pygments-style: autumn
:revealjs_theme: simple
:revealjs_transition: none
:revealjs_width: 1280
:revealjs_height: 960
:revealjs_margin: 0.04
:revealjs_history: false
// :revealjsdir: https://wackywendell.github.io/reveal.js/
:revealjsdir: ..
// :revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.0.0/
:stem: latexmath
:imagesdir: imgs
// :toc:

== Rearrangements

video::rearrange_n100_s68_F0.005.mp4[height=720, options="autoplay,loop"]

=== Micro-Rearrangements

video::micro-rearrange_n100_s22_F0.001.mp4[height=800, options="autoplay,loop"]

=== Quantifying Rearrangements

 - Run a standard hard sphere simulation for a long time.
 - At 1000 different points, take a snapshot.
 - Plug the snapshot into a packing minimizer, and see what packing each snapshot gives.
 - Quantify how many of these snapshot packings are the same or different from previous snapshots.
   
== Quantifying Rearrangements

image::inherent_found_n100_t100.svg["", 60%, title="", caption="", align=center]

=== Step Distributions

// \( \Delta \phi = 10^{-3} \)

[cols="^a,^a",grid="none",frame="none"]
|==================================

| Close to Jamming
| Glassy 

| \( \Delta \phi = \phi - \phi_J = -10^{-4} \)
| \( \phi = 0.59 \), \( \Delta \phi = -0.05 \)

| image::hsdphi_steps_d0.0001_t100_n40.svg["", 100%, title="", caption="", align=center]
| image::hs_steps_F0.59.svg["", 100%, title="", caption="", align=center]

|==================================

=== Step Distributions

Low Δφ

image::cartoon-rearrange-lowphi.svg["", 50%, title="", caption="", align=center]

Systems are completely fixed, unable to rearrange at all.

=== Step Distributions

Moderate Δφ

image::cartoon-rearrange-midphi.svg["", 50%, title="", caption="", align=center]

Some systems are able to rearrange, but only as micro-rearrangements.

=== Step Distributions

Large Δφ

image::cartoon-rearrange-highphi-arrow.svg["", 50%, title="", caption="", align=center]

Some systems are still stuck in micro-rearrangements, but many can fully rearrange.

As density decreases, more and more systems will be able to rearrange.

=== Hypothesis

Rearranging systems are glassy, and could be modeled as caged at short times, and as a random-walk from packing to packing at long times.
